---
services:
  web:
    build:
      context: ./src/webclient/
      dockerfile: Dockerfile
      target: runner
    image: webclient:latest
    container_name: webclient
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
